// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCityOps.Infrastructure.Persistence;

#nullable disable

namespace SmartCityOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818071436_ExpandFieldUnitSeedData")]
    partial class ExpandFieldUnitSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCityOps.Domain.Entities.FieldUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UnitCode")
                        .IsUnique();

                    b.ToTable("FieldUnits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9599661-cb85-422a-ae1e-3596a0be4976"),
                            Latitude = 39.924999999999997,
                            Longitude = 32.835999999999999,
                            Status = "Available",
                            Type = "Police",
                            UnitCode = "POL-01"
                        },
                        new
                        {
                            Id = new Guid("96f71bc3-185a-4148-b6e5-2a67daca36f5"),
                            Latitude = 39.950000000000003,
                            Longitude = 32.799999999999997,
                            Status = "Available",
                            Type = "Police",
                            UnitCode = "POL-02"
                        },
                        new
                        {
                            Id = new Guid("fbeba342-a43c-40ed-9465-f50a4177ccf7"),
                            Latitude = 39.899999999999999,
                            Longitude = 32.899999999999999,
                            Status = "Available",
                            Type = "Police",
                            UnitCode = "POL-03"
                        },
                        new
                        {
                            Id = new Guid("2ac082fc-7044-4b45-8404-f018d6209477"),
                            Latitude = 39.93,
                            Longitude = 32.850000000000001,
                            Status = "Available",
                            Type = "Medical",
                            UnitCode = "MED-01"
                        },
                        new
                        {
                            Id = new Guid("6b68f2df-e043-48e2-a800-6f26bf4ed843"),
                            Latitude = 39.960000000000001,
                            Longitude = 32.829999999999998,
                            Status = "Available",
                            Type = "Medical",
                            UnitCode = "MED-02"
                        },
                        new
                        {
                            Id = new Guid("4e2e9af5-cf12-4270-bfc3-f641cf3d815f"),
                            Latitude = 39.880000000000003,
                            Longitude = 32.789999999999999,
                            Status = "Available",
                            Type = "Medical",
                            UnitCode = "MED-03"
                        },
                        new
                        {
                            Id = new Guid("145eeb0d-ef83-41bd-994b-083e5a6c92d1"),
                            Latitude = 39.914999999999999,
                            Longitude = 32.82,
                            Status = "Available",
                            Type = "Fire",
                            UnitCode = "FIR-01"
                        },
                        new
                        {
                            Id = new Guid("833f2afc-9565-497d-8bb2-75403aab7127"),
                            Latitude = 39.920000000000002,
                            Longitude = 32.880000000000003,
                            Status = "Available",
                            Type = "Fire",
                            UnitCode = "FIR-02"
                        },
                        new
                        {
                            Id = new Guid("5a6fcd12-2798-432c-81a6-416c00d5c30f"),
                            Latitude = 39.869999999999997,
                            Longitude = 32.829999999999998,
                            Status = "OutOfService",
                            Type = "Fire",
                            UnitCode = "FIR-03"
                        },
                        new
                        {
                            Id = new Guid("d5dd3221-bd61-417c-9350-8bd21b732f9b"),
                            Latitude = 39.939999999999998,
                            Longitude = 32.859999999999999,
                            Status = "Available",
                            Type = "UtilityCrew",
                            UnitCode = "UTL-01"
                        },
                        new
                        {
                            Id = new Guid("c05d230d-78b1-41ed-be18-c7936616b0ae"),
                            Latitude = 39.969999999999999,
                            Longitude = 32.869999999999997,
                            Status = "Available",
                            Type = "UtilityCrew",
                            UnitCode = "UTL-02"
                        },
                        new
                        {
                            Id = new Guid("12ad0bf6-b819-40e7-95d8-093ff4b9ac19"),
                            Latitude = 39.909999999999997,
                            Longitude = 32.789999999999999,
                            Status = "Available",
                            Type = "UtilityCrew",
                            UnitCode = "UTL-03"
                        },
                        new
                        {
                            Id = new Guid("cc32593c-0ab6-4c24-aaea-f6bb9ab2de95"),
                            Latitude = 39.905000000000001,
                            Longitude = 32.810000000000002,
                            Status = "OutOfService",
                            Type = "TrafficControl",
                            UnitCode = "TRF-01"
                        },
                        new
                        {
                            Id = new Guid("40adac57-adbc-42fb-b833-2ff44c976106"),
                            Latitude = 39.93,
                            Longitude = 32.789999999999999,
                            Status = "Available",
                            Type = "TrafficControl",
                            UnitCode = "TRF-02"
                        },
                        new
                        {
                            Id = new Guid("115b0f76-4adf-4c9e-9d43-432b18143449"),
                            Latitude = 39.890000000000001,
                            Longitude = 32.869999999999997,
                            Status = "OutOfService",
                            Type = "TrafficControl",
                            UnitCode = "TRF-03"
                        });
                });

            modelBuilder.Entity("SmartCityOps.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentCode")
                        .IsUnique();

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("SmartCityOps.Domain.Entities.OperationalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FieldUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FieldUnitId");

                    b.HasIndex("IncidentId");

                    b.ToTable("OperationalTasks", (string)null);
                });

            modelBuilder.Entity("SmartCityOps.Domain.Entities.OperationalTask", b =>
                {
                    b.HasOne("SmartCityOps.Domain.Entities.FieldUnit", null)
                        .WithMany()
                        .HasForeignKey("FieldUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCityOps.Domain.Entities.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
